version: "3.8"

services:
  controller:
    build: ./controller
    restart: always
    ports:
      - "8001:8001"
    networks:
      - backend

  # position:
  #   build: ./position
  #   image: position:latest
  #   restart: always
  #   ports:
  #     - "8002:8002"
  #   networks:
  #     - backend

  aum:
    build: ./aum
    depends_on:
      - controller
    image: aum:latest
    restart: always
    networks:
      - backend

  # fill:
  #   build: ./fill
  #   depends_on:
  #     - controller    
  #   image: fill:latest
  #   restart: always
  #   networks:
  #     - backend

networks:
  backend:
    external: true
