version: "3.8"

services:
  controller:
    build: ./controller
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
    - ./controller/:/app/   
    ports:
      - "8004:8000"
    restart: always

  position:
    build: ./position
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
    - ./position/:/app/
    ports:
      - "8003:8000"
    restart: always

  aum:
    build: ./aum
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
    - ./aum/:/app/
    depends_on:
      - controller
    ports:
      - 8002:8000
    restart: always

  fill:
    build: ./fill
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
    - ./fill/:/app/
    depends_on:
      - controller    
    ports:
      - 8001:8000
    restart: always
